### ISSUE TITLE
broken page layout

### ISSUE THREAD

**Issue by Julien00859** [w4/bin#16]
Hello,

I'm running bin v1.0.4 on Debian. I was use to publish bins via curl, it was fine on v1.0.2 but with the latest version the layout is broken.

See by yourself: https://bin.drlazor.be/ilshummurl

The command I used was as follow:

    $ cat <<EOF | curl -s -X PUT --data-binary @- https://bin.drlazor.be
    pipe heredoc> hello
    pipe heredoc> world
    pipe heredoc> this
    pipe heredoc> is
    pipe heredoc> a
    pipe heredoc> test
    pipe heredoc> EOF

This only affect publishing bins via curl, via the web page it works fine.

**Comment by w4** [comment]
That certainly is a regression, sorry about that. I believe what's going on is the `replace("\n", "</code><code>")` works fine when posting from your browser on a fluke because the text field is sending `\r\n`s so the `\r` is retained and interpreted by the browser as a newline, whereas your terminal (quite rightly) is just sending the `\n` so the newline itself is being replaced.

Should be an easy fix, I'll get a new release cut for you shortly
